/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as NewsRouteImport } from './routes/news'
import { Route as StandorteRouteImport } from './routes/standorte'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as SortimentIndexRouteImport } from './routes/sortiment.index'
import { Route as SortimentSlugRouteImport } from './routes/sortiment.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const StandorteRoute = StandorteRouteImport.update({
  id: '/standorte',
  path: '/standorte',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const SortimentIndexRoute = SortimentIndexRouteImport.update({
  id: '/sortiment/',
  path: '/sortiment/',
  getParentRoute: () => rootRouteImport,
} as any)
const SortimentSlugRoute = SortimentSlugRouteImport.update({
  id: '/sortiment/$slug',
  path: '/sortiment/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/news': typeof NewsRoute
  '/standorte': typeof StandorteRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/sortiment/$slug': typeof SortimentSlugRoute
  '/sortiment/': typeof SortimentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/news': typeof NewsRoute
  '/standorte': typeof StandorteRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/sortiment/$slug': typeof SortimentSlugRoute
  '/sortiment': typeof SortimentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/news': typeof NewsRoute
  '/standorte': typeof StandorteRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/sortiment/$slug': typeof SortimentSlugRoute
  '/sortiment/': typeof SortimentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontakt'
    | '/news'
    | '/standorte'
    | '/ueber-uns'
    | '/sortiment/$slug'
    | '/sortiment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kontakt'
    | '/news'
    | '/standorte'
    | '/ueber-uns'
    | '/sortiment/$slug'
    | '/sortiment'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/news'
    | '/standorte'
    | '/ueber-uns'
    | '/sortiment/$slug'
    | '/sortiment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  NewsRoute: typeof NewsRoute
  StandorteRoute: typeof StandorteRoute
  UeberUnsRoute: typeof UeberUnsRoute
  SortimentSlugRoute: typeof SortimentSlugRoute
  SortimentIndexRoute: typeof SortimentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standorte': {
      id: '/standorte'
      path: '/standorte'
      fullPath: '/standorte'
      preLoaderRoute: typeof StandorteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sortiment/': {
      id: '/sortiment/'
      path: '/sortiment'
      fullPath: '/sortiment/'
      preLoaderRoute: typeof SortimentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sortiment/$slug': {
      id: '/sortiment/$slug'
      path: '/sortiment/$slug'
      fullPath: '/sortiment/$slug'
      preLoaderRoute: typeof SortimentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  NewsRoute: NewsRoute,
  StandorteRoute: StandorteRoute,
  UeberUnsRoute: UeberUnsRoute,
  SortimentSlugRoute: SortimentSlugRoute,
  SortimentIndexRoute: SortimentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
